/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.BaseDatos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author anfel
 */
public class MenuProfesional extends javax.swing.JFrame {

    /**
     * Creates new form MenuProfesional
     */
    
    private static GestionarProfesional gestionarProfesional;
    private static GestionarPropietario gestionarPropietario;
    private int xMouse, yMouse;
    private final BaseDatos bd;
    
    public MenuProfesional() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/Vista/Imagenes/AvatarVeterinario.png");
        bd = new BaseDatos();
        tblPanel.setVisible(false);
        btnAgregarProfesional.setVisible(false);
        btnActualizar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnGestionarProfesionales = new javax.swing.JPanel();
        lblGestionarProfesionales = new javax.swing.JLabel();
        btnGestionarPropietarios = new javax.swing.JPanel();
        lblGestionarPropietarios = new javax.swing.JLabel();
        btnConfiguraciones = new javax.swing.JPanel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblBienvenido = new java.awt.Label();
        tblPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfesionales = new javax.swing.JTable();
        btnAgregarProfesional = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 77, 0));

        btnGestionarProfesionales.setBackground(new java.awt.Color(110, 77, 0));
        btnGestionarProfesionales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblGestionarProfesionales.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblGestionarProfesionales.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarProfesionales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarProfesionales.setText("GESTIONAR PROFESIONALES");
        lblGestionarProfesionales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarProfesionalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGestionarProfesionalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGestionarProfesionalesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGestionarProfesionalesLayout = new javax.swing.GroupLayout(btnGestionarProfesionales);
        btnGestionarProfesionales.setLayout(btnGestionarProfesionalesLayout);
        btnGestionarProfesionalesLayout.setHorizontalGroup(
            btnGestionarProfesionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionarProfesionales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btnGestionarProfesionalesLayout.setVerticalGroup(
            btnGestionarProfesionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionarProfesionales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        btnGestionarPropietarios.setBackground(new java.awt.Color(110, 77, 0));

        lblGestionarPropietarios.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblGestionarPropietarios.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarPropietarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarPropietarios.setText("GESTIONAR PROPIETARIOS");
        lblGestionarPropietarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGestionarPropietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarPropietariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGestionarPropietariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGestionarPropietariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGestionarPropietariosLayout = new javax.swing.GroupLayout(btnGestionarPropietarios);
        btnGestionarPropietarios.setLayout(btnGestionarPropietariosLayout);
        btnGestionarPropietariosLayout.setHorizontalGroup(
            btnGestionarPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionarPropietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnGestionarPropietariosLayout.setVerticalGroup(
            btnGestionarPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGestionarPropietariosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblGestionarPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnConfiguraciones.setBackground(new java.awt.Color(110, 77, 0));
        btnConfiguraciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblCerrarSesion.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrarSesion.setText("CERRAR SESIÓN");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConfiguracionesLayout = new javax.swing.GroupLayout(btnConfiguraciones);
        btnConfiguraciones.setLayout(btnConfiguracionesLayout);
        btnConfiguracionesLayout.setHorizontalGroup(
            btnConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnConfiguracionesLayout.setVerticalGroup(
            btnConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        lblAvatar.setBackground(new java.awt.Color(255, 255, 255));
        lblAvatar.setForeground(new java.awt.Color(255, 255, 255));
        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("FOTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGestionarProfesionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConfiguraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnGestionarPropietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnGestionarProfesionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGestionarPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfiguraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 560));

        exitPanel.setBackground(new java.awt.Color(255, 255, 255));
        exitPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exitPanelMouseDragged(evt);
            }
        });
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitPanelMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        lblExit.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblExit.setForeground(new java.awt.Color(0, 0, 0));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 960, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        lblBienvenido.setAlignment(java.awt.Label.CENTER);
        lblBienvenido.setFont(new java.awt.Font("Roboto Black", 1, 28)); // NOI18N
        lblBienvenido.setText("BIENVENIDO PROFESIONAL");

        tblPanel.setBackground(new java.awt.Color(204, 204, 204));

        tblProfesionales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProfesionales);

        javax.swing.GroupLayout tblPanelLayout = new javax.swing.GroupLayout(tblPanel);
        tblPanel.setLayout(tblPanelLayout);
        tblPanelLayout.setHorizontalGroup(
            tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        tblPanelLayout.setVerticalGroup(
            tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnAgregarProfesional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProfesionalMouseClicked(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAgregarProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(tblPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 810, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGestionarProfesionalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarProfesionalesMouseClicked
        bd.mostrarProfesionales(tblProfesionales);
        
        btnAgregarProfesional.setText("Agregar Profesional");
        
        tblPanel.setVisible(true);
        btnAgregarProfesional.setVisible(true);
        btnActualizar.setVisible(true);
        
        //JOptionPane.showMessageDialog(this, "Me presionaste");
        
        /*gestionarProfesional = new GestionarProfesional();
        gestionarProfesional.setVisible(true);*/
    }//GEN-LAST:event_lblGestionarProfesionalesMouseClicked

    private void lblGestionarProfesionalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarProfesionalesMouseEntered
        btnGestionarProfesionales.setBackground(Color.WHITE);
        lblGestionarProfesionales.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblGestionarProfesionalesMouseEntered

    private void lblGestionarProfesionalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarProfesionalesMouseExited
        btnGestionarProfesionales.setBackground(new Color(110, 77, 0));
        lblGestionarProfesionales.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblGestionarProfesionalesMouseExited

    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        btnConfiguraciones.setBackground(Color.WHITE);
        lblCerrarSesion.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
         btnConfiguraciones.setBackground(new Color(110, 77, 0));
         lblCerrarSesion.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        bd.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        exitBtn.setBackground(Color.red);
        lblExit.setForeground(Color.white);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        exitBtn.setBackground(Color.white);
        lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    private void exitPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_exitPanelMouseDragged

    private void exitPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_exitPanelMousePressed

    private void lblGestionarPropietariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPropietariosMouseClicked
        bd.mostrarPropietarios(tblProfesionales);
        
        btnAgregarProfesional.setText("Agregar Propietario");
        
        tblPanel.setVisible(true);
        btnAgregarProfesional.setVisible(true);
        btnActualizar.setVisible(true);
        
    }//GEN-LAST:event_lblGestionarPropietariosMouseClicked

    private void lblGestionarPropietariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPropietariosMouseEntered
        btnGestionarPropietarios.setBackground(Color.WHITE);
        lblGestionarPropietarios.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblGestionarPropietariosMouseEntered

    private void lblGestionarPropietariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarPropietariosMouseExited
        btnGestionarPropietarios.setBackground(new Color(110, 77, 0));
        lblGestionarPropietarios.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblGestionarPropietariosMouseExited

    private void btnAgregarProfesionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProfesionalMouseClicked
        
        //Configurar el botón para que identifique cuándo se muestran los propietarios y los profesionales.
        
        if(btnAgregarProfesional.getText().equals("Agregar Profesional")){
            gestionarProfesional = new GestionarProfesional();
            gestionarProfesional.setVisible(true);
        } else{
            gestionarPropietario = new GestionarPropietario();
            gestionarPropietario.setVisible(true);
        }
        
        
    }//GEN-LAST:event_btnAgregarProfesionalMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        bd.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        if(btnAgregarProfesional.getText().equals("Agregar Profesional")){
            bd.mostrarProfesionales(tblProfesionales);
        } else{
            bd.mostrarPropietarios(tblProfesionales);
        }
    }//GEN-LAST:event_btnActualizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarProfesional;
    private javax.swing.JPanel btnConfiguraciones;
    private javax.swing.JPanel btnGestionarProfesionales;
    private javax.swing.JPanel btnGestionarPropietarios;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private java.awt.Label lblBienvenido;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGestionarProfesionales;
    private javax.swing.JLabel lblGestionarPropietarios;
    private javax.swing.JPanel tblPanel;
    public javax.swing.JTable tblProfesionales;
    // End of variables declaration//GEN-END:variables
}
